# Generated by Django 4.2.22 on 2025-06-06 20:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gpsdevice",
            options={
                "verbose_name": "GPS Device",
                "verbose_name_plural": "GPS Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="gpsevent",
            options={"verbose_name": "GPS Event", "verbose_name_plural": "GPS Events"},
        ),
        migrations.AlterModelOptions(
            name="gpslocation",
            options={
                "verbose_name": "GPS Location",
                "verbose_name_plural": "GPS Locations",
            },
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="altitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="battery_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="course",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="firmware_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="imei",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="last_log",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="last_maintenance",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="maintenance_interval",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="odometer",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="position",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="protocol",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="signal_strength",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="speed",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="gpsdevice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="course",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="gps.gpsdevice",
            ),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="odometer",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="position",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="gpsevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("TRACK", "Track"),
                    ("IO", "Input/Output"),
                    ("ALERT", "Alert"),
                    ("STATUS", "Status"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="accuracy",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="altitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="course",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="gps.gpsdevice",
            ),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="fix_quality",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="fix_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="hdop",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="pdop",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="position",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="satellites",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="speed",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gpslocation",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="WiFiAccessPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mac_address", models.CharField(max_length=17)),
                ("signal_strength", models.IntegerField()),
                ("ssid", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "WiFi Access Point",
                "verbose_name_plural": "WiFi Access Points",
                "unique_together": {("mac_address",)},
            },
        ),
        migrations.CreateModel(
            name="CellTower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mcc", models.IntegerField()),
                ("mnc", models.IntegerField()),
                ("lac", models.IntegerField()),
                ("cell_id", models.BigIntegerField()),
                ("signal_strength", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cell Tower",
                "verbose_name_plural": "Cell Towers",
                "unique_together": {("mcc", "mnc", "lac", "cell_id")},
            },
        ),
    ]
