# Generated by Django 4.2.22 on 2025-06-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0002_alter_gpsdevice_options_alter_gpsevent_options_and_more"),
        ("gps", "0002_convert_raw_data"),
    ]

    operations = []
