# Generated by Django 4.2.22 on 2025-06-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0004_raw_data_jsonb_to_bytea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpsevent",
            name="raw_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
