# Generated by Django 5.2.3 on 2025-06-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0008_transfer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsevent',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
