# Generated by Django 5.2.3 on 2025-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0010_cardtransaction_accelerationlog_addresscache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
