# Generated by Django 4.2.22 on 2025-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0011_gpsdevice_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpsdevice",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("tcp", "TCP"),
                    ("udp", "UDP"),
                    ("gprs", "GPRS"),
                ],
                default="default",
                max_length=10,
                verbose_name="protocol",
            ),
        ),
    ]
