# Generated by Django 4.2.22 on 2025-06-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0012_gpsdevice_protocol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gpsdevice",
            name="protocol",
        ),
    ]
