# Generated by Django 4.2.22 on 2025-06-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0013_remove_gpsdevice_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpsdevice",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("concox", "Concox"),
                    ("meiligao", "Meiligao"),
                    ("wialon", "Wialon"),
                ],
                default="concox",
                max_length=20,
                verbose_name="protocol",
            ),
        ),
    ]
