# Generated by Django 5.2.3 on 2025-06-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0014_gpsdevice_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='license plate')),
                ('make', models.CharField(max_length=50, verbose_name='make')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('year', models.IntegerField(verbose_name='year')),
                ('color', models.CharField(max_length=30, verbose_name='color')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Automóvil'), ('TRUCK', 'Camión'), ('MOTORCYCLE', 'Motocicleta'), ('BUS', 'Autobús'), ('VAN', 'Camioneta'), ('OTHER', 'Otro')], default='CAR', max_length=20, verbose_name='vehicle type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('MAINTENANCE', 'En mantenimiento'), ('REPAIR', 'En reparación')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN')),
                ('economico', models.CharField(blank=True, max_length=20, null=True, verbose_name='economic number')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasolina'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Eléctrico'), ('HYBRID', 'Híbrido'), ('GAS', 'Gas')], default='GASOLINE', max_length=20, verbose_name='fuel type')),
                ('engine_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='engine size')),
                ('passenger_capacity', models.IntegerField(blank=True, null=True, verbose_name='passenger capacity')),
                ('cargo_capacity', models.FloatField(blank=True, null=True, verbose_name='cargo capacity (kg)')),
                ('insurance_policy', models.CharField(blank=True, max_length=50, null=True, verbose_name='insurance policy')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='insurance expiry')),
                ('registration_expiry', models.DateField(blank=True, null=True, verbose_name='registration expiry')),
                ('mileage', models.FloatField(default=0, verbose_name='mileage (km)')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='last service date')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='next service date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='gps.gpsdevice', verbose_name='GPS device')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='gps.driver', verbose_name='assigned driver')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['plate'],
            },
        ),
    ]
