# Generated by Django 5.2.3 on 2025-07-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0015_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_tracking_sessions', to='gps.gpsdevice'),
        ),
    ]
