# Generated by Django 4.2.22 on 2025-07-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0015_vehicle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simcard",
            options={"verbose_name": "SIM card", "verbose_name_plural": "SIM cards"},
        ),
    ]
