# Generated by Django 4.2.22 on 2025-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0016_alter_tracking_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="geofence",
            name="alert_on_entry",
            field=models.BooleanField(
                default=False, help_text="Show alert when device enters geofence"
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="alert_on_exit",
            field=models.BooleanField(
                default=False, help_text="Show alert when device exits geofence"
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="color",
            field=models.CharField(
                default="#3388ff", help_text="Fill color in hex format", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="devices",
            field=models.ManyToManyField(
                blank=True, related_name="geofences", to="gps.gpsdevice"
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="notification_cooldown",
            field=models.IntegerField(
                default=300, help_text="Minimum seconds between notifications"
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="notify_emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of email addresses for notifications",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="notify_sms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of phone numbers for SMS notifications",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="stroke_color",
            field=models.CharField(
                default="#3388ff", help_text="Border color in hex format", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="stroke_width",
            field=models.IntegerField(default=2, help_text="Border width in pixels"),
        ),
    ]
