# Generated by Django 4.2.22 on 2025-07-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gps", "0015_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(max_length=100, verbose_name="driver name"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total amount"
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="received amount"
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="difference"
                    ),
                ),
                (
                    "ticket_data",
                    models.JSONField(default=dict, verbose_name="ticket data"),
                ),
                ("report_date", models.DateField(verbose_name="report date")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_reports",
                        to="gps.gpsdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket report",
                "verbose_name_plural": "ticket reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="StatisticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="report date")),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total distance"
                    ),
                ),
                (
                    "total_passengers",
                    models.IntegerField(default=0, verbose_name="total passengers"),
                ),
                (
                    "total_tickets",
                    models.IntegerField(default=0, verbose_name="total tickets"),
                ),
                (
                    "average_speed",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="average speed"
                    ),
                ),
                (
                    "operating_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="operating hours"
                    ),
                ),
                (
                    "statistics_data",
                    models.JSONField(default=dict, verbose_name="statistics data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics_reports",
                        to="gps.gpsdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "statistics report",
                "verbose_name_plural": "statistics reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket Report"),
                            ("stats", "Statistics Report"),
                            ("people", "People Count Report"),
                            ("alarm", "Alarm Report"),
                            ("sensor", "Sensor Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                        verbose_name="report type",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("xlsx", "Excel"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="format",
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(default=dict, verbose_name="template data"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "report template",
                "verbose_name_plural": "report templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="parameters"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/",
                        verbose_name="result file",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "report execution",
                "verbose_name_plural": "report executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PeopleCountReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="report date")),
                (
                    "total_people",
                    models.IntegerField(default=0, verbose_name="total people"),
                ),
                (
                    "peak_hour",
                    models.TimeField(blank=True, null=True, verbose_name="peak hour"),
                ),
                (
                    "peak_count",
                    models.IntegerField(default=0, verbose_name="peak count"),
                ),
                (
                    "hourly_data",
                    models.JSONField(default=dict, verbose_name="hourly data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_count_reports",
                        to="gps.gpsdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "people count report",
                "verbose_name_plural": "people count reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="AlarmReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="report date")),
                (
                    "total_alarms",
                    models.IntegerField(default=0, verbose_name="total alarms"),
                ),
                (
                    "critical_alarms",
                    models.IntegerField(default=0, verbose_name="critical alarms"),
                ),
                (
                    "warning_alarms",
                    models.IntegerField(default=0, verbose_name="warning alarms"),
                ),
                (
                    "alarm_types",
                    models.JSONField(default=dict, verbose_name="alarm types"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_reports",
                        to="gps.gpsdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "alarm report",
                "verbose_name_plural": "alarm reports",
                "ordering": ["-report_date"],
            },
        ),
    ]
